eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false

  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

management:
  zipkin:
    tracing:
      sampling:
        probability: 1.0