spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctioncartservicedb
    username: postgres
    password: Mypassword1234
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8285

application:
  config:
    cart-url: http://localhost:8222/api/v1/carts
    product-url: http://localhost:8222/api/v1/products


