spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctionproductservicedb
    username: postgres
    password: Mypassword1234
    platform: postgresql

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: bidWinnerConfirmation:com.auction.product.kafka.BidWinnerConfirmation
        max.request.size: 125829120

server:
  port: 8484

bidding:
  duration-minutes: 3
