spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auctionProductServiceDb
    username: postgres
    password: Mypassword1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # use 'update' for incremental schema updates in dev
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8484

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs



      #spring:
  #datasource:
   # url: jdbc:postgresql://localhost:5433/auctionProductServiceDb?user=postgres&password=Mypassword1234

  #jpa:
    #hibernate:
      #ddl-auto: create


#spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5433/auctionProductServiceDb
    #username: postgres
   # password: Mypassword1234
    #driver-class-name: org.postgresql.Driver

  #jpa:
    #hibernate:
      #ddl-auto: create
      #database: postgresql
      #database-platform: org.hibernate.dialect.PostgreSQLDialect
    #show-sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
#datasource:
  #url: jdbc:postgresql://localhost:5433/auctionProductServiceDb?user=postgres&password=Mypassword1234
  #jpa:
    #hibernate:
      #ddl-auto: create
  #doc:
    #swagger-ui:
      #path: /swagger-ui.html
    #api-docs:
      #path: /api-docs

#server:
  #port: 8484



    #spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5433/auctionProductServiceDb?user=postgres&password=Mypassword1234

  #jpa:
    #hibernate:
      #ddl-auto: create
    #show-sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
  #jpa:
    #hibernate:
      #ddl-auto: create


    #spring:
  #datasource:
    #url:
    #jdbc:postgresql://localhost:5433/auctionPaymentServiceDb?user=postgres&password=Mypassword1234#spring:
  #datasource:
   #url: jdbc:postgresql://localhost:5433/auctionProductServiceDb
    #username: postgres
    #password: Mypassword1234
    #driver-class-name: org.postgresql.Driver
    #platform: postgresql

  #jpa:
    #hibernate:
      #ddl-auto: create
    #show-sql: true
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    #properties:
    #hibernate:
    #dialect: org.hibernate.dialect.PostgreSQLDialect

    #flyway:
    #enabled: true
    # baseline-on-migrate: true
    # baseline-description: "init"
    # baseline-version: 0
    # user: postgres
    #password: Mypassword1234

#productService:
  #url: http://localhost:8484

#server:
  #port: 8484

#spring-doc:
  #swagger-ui:
    #path: /swagger-ui.html
  #api-docs:
    #path: /api-docs



