spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auctionProductServiceDb
    username: postgres
    password: Mypassword1234
    platform: postgresql
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8484