spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auctionUserServiceDb?user=postgres&password=Mypassword1234
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      #show-sql: true
      #database-platform: org.hibernate.dialect.PostgreSQLDialect
      #properties:
        #hibernate:
          #dialect: org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.url=jdbc:postgresql://localhost:5433/auctionUserServiceDb?user=postgres&password=Mypassword1234

# DataSource Configuration
#spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5433/auctionUserServiceDb
    #username: postgres
    #password: Mypassword1234
    #host: localhost
    #driver-class-name: org.postgresql.Driver
    #platform: postgresql

  #jpa:
    #hibernate:
      #ddl-auto: create
      #show-sql: true
      #properties:
        #hibernate:
          #dialect: org.hibernate.dialect.PostgreSQLDialect
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect

  #doc:
    #swagger-ui:
      #path: /swagger-ui.html
    #api-docs:
      #path: /api-docs

  #flyway:
    #enabled: true
    #baseline-on-migrate: true
    #baseline-description: init
    #baseline-version: 0
    #user: postgres
    #password: Mypassword1234

# External service URL
#userService:
  #url: http://localhost:8585

# Server Configuration
server:
  port: 8580
